version: "3"
services:
  server:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      JWT_TOKEN_EXPIRES_IN: 20m
      USER_STARTING_BALANCE: 5000
      PASSWORD_MIN: 8
      PASSWORD_MAX: 72
      #these variables should be managed with docker secrets
      DB_URI: postgresql://postgres:pwd@postgres:5432/arithmetic-calculator
      AWS_ACCESS_KEY_ID: AWS ACCESS KEY ID goes here
      AWS_SECRET_ACCESS_KEY: AWS SECRET ACCESS KEY goes here

    ports:
      - "9001:9000"
    command: npm run start

  postgres:
    image: postgres:15.2
    user: postgres
    ports:
      - "15432:5432"
    environment:
      #this info would be managed with docker secrets
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: arithmetic-calculator
